import numpy as np
import matplotlib.pyplot as plt
from fractions import Fraction

# -------------------------------------------------------------------------
# 1. CORE PARAMETERS FROM THE JOHNSON HARMONIC FRAMEWORK
# -------------------------------------------------------------------------
# Distance coordinate: h = 181/3
h = Fraction(181, 3)
c = 3
f_s = h / c  # 181/9 = 20.1111...
spatial_remainder = float(f_s - 20)  # 1/9

# Temporal frequency fraction: f_t = 1 - 43/120 = 77/120
lunar_motion = Fraction(43, 120)
f_t = float(1 - lunar_motion)

# Metonic drift constant: epsilon = 235/19 - 12 = 7/19
epsilon = float(Fraction(235, 19) - 12)

# Lattice Scalar from Admissibility Lock (R=4)
lambda_scalar = 24

# Total Calculated Wave Peaks (1778/855 ~ 2.0795)
total_wave_peaks = (spatial_remainder * f_t * lambda_scalar) + epsilon

# -------------------------------------------------------------------------
# 2. PLOT SETUP
# -------------------------------------------------------------------------
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6.5))
fig.suptitle("Earth-Moon Harmonic Framework & Tidal Geometry\nAuthor: Carolina Johnson (CJ)", 
             fontsize=14, fontweight='bold', color='#1a1a1a')

# Time arrays for simulation
theta_spatial = np.linspace(0, 2 * np.pi, 1000)
time_metonic = np.linspace(0, 19, 1000)  # 19-year cycle horizon

# -------------------------------------------------------------------------
# LEFT PLOT: THE METONIC RESIDUAL RESONANCE (TIME-DOMAIN)
# -------------------------------------------------------------------------
# Showing the alignment of the 235 months across the 19-year lattice grid
months_per_year = 235 / 19
harmonic_drift_wave = np.sin(2 * np.pi * months_per_year * time_metonic)
decay_envelope = np.exp(-time_metonic * epsilon) # 1/e intrinsic limit decay

ax1.plot(time_metonic, harmonic_drift_wave, color='#2b5c8f', alpha=0.4, label='Lunisolar Modulation')
ax1.plot(time_metonic, decay_envelope, color='#d95f02', linewidth=2.5, linestyle='--', 
         label=f'Intrinsic Decay Envelope (ε = 7/19 ≈ 1/e)')

# Highlight the integer closure boundaries
for year in [0, 19]:
    ax1.axvline(x=year, color='#4d4d4d', linestyle=':', alpha=0.7)

ax1.set_title("Metonic Residual & Intrinsic Decay Horizon", fontsize=11, fontweight='bold')
ax1.set_xlabel("Lattice Depth Horizon (Years, R=4 Domain)", fontsize=10)
ax1.set_ylabel("Resonance Amplitude", fontsize=10)
ax1.grid(True, linestyle=':', alpha=0.5)
ax1.legend(loc='upper right', frameon=True, facecolor='white', edgecolor='none')
ax1.set_xlim(-0.5, 19.5)

# -------------------------------------------------------------------------
# RIGHT PLOT: THE STRUCTURAL TIDAL NODES (SPATIAL-DOMAIN)
# -------------------------------------------------------------------------
# Plotting the fundamental quadrupole wave generated by the rational interaction
# The wave expression uses the total derived wave peak parameter (~2.0795)
wave_amplitude = np.cos(total_wave_peaks * theta_spatial)

ax2.plot(theta_spatial, wave_amplitude, color='#2c7bb6', linewidth=2.5, 
         label=f'Tidal Wave Template (Nodes = {total_wave_peaks:.4f})')

# Mark the exact anti-nodes (The 2 Mandated High Tide Peaks)
peak_indices = [0, len(theta_spatial)//2, len(theta_spatial)-1]
ax2.scatter(theta_spatial[peak_indices], wave_amplitude[peak_indices], 
            color='#d7191c', s=100, zorder=5, label='Mandated High Tide Anti-Nodes')

# Format the x-axis with spatial degree markings
ax2.set_xticks([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
ax2.set_xticklabels(['0°\n(Near Node)', '90°\n(Low Tide)', '180°\n(Far Node)', '270°\n(Low Tide)', '360°\n(Closure)'])

ax2.set_title("Spatial Quadrupole Distribution per Rotation", fontsize=11, fontweight='bold')
ax2.set_xlabel("Angular Displacement Along Earth Circumference", fontsize=10)
ax2.set_ylabel("Structural Displacements", fontsize=10)
ax2.axhline(0, color='black', linewidth=0.8, alpha=0.3)
ax2.grid(True, linestyle=':', alpha=0.5)
ax2.legend(loc='lower right', frameon=True, facecolor='white', edgecolor='none')
ax2.set_ylim(-1.3, 1.3)

# -------------------------------------------------------------------------
# METRIC ANNOTATION PANEL (BOTTOM)
# -------------------------------------------------------------------------
metadata_text = (
    f"Distance Coordinate (h): 181/3\n"
    f"Spatial Frequency Remainder: {Fraction(1, 9)}\n"
    f"Temporal Daily Motion Modifier: {Fraction(77, 120)}\n"
    f"Lattice Scalar (Λ): {lambda_scalar} (Derived via R=4)\n"
    f"Rational Tidal Product: 1778/855 ≈ {float(total_wave_peaks):.4f}\n"
    f"Mandated Wave Peaks: 2 (Integer Part)\n"
    f"Calculated Daily Lag: {24 * (float(total_wave_peaks) - 2) * 60 / 2:.1f} minutes"
)

fig.text(0.5, -0.05, metadata_text, ha='center', va='center', fontsize=10,
         bbox=dict(boxstyle='round,pad=0.6', facecolor='#f7f7f7', edgecolor='#cccccc', alpha=0.9))

plt.tight_layout()
plt.show()
